### ISSUE TITLE
how to build demo with javac 

### ISSUE THREAD

**Issue by fzwqq** [pytorch/java-demo#10]
Thanks for the tutorial. 

Well, could you pls write a guide start from javac for the users who are not familiar with Gradle. 

Thanks again.
---
when running the app, I had always got this.
![image](https://user-images.githubusercontent.com/12872935/80546590-55842c00-89b6-11ea-937f-53363d729906.png)

**Comment by fzwqq** [comment]
![image](https://user-images.githubusercontent.com/12872935/80534641-d7b52600-899f-11ea-9534-675946b8f267.png)
By the way,  when I do as the tutorial step by step, it occurs the error?  My system is ubuntu18 and download Pre-cxx11 ABI. Also, I set my Libtorch rightly.

**Comment by dreiss** [comment]
Make sure you're using the same version of libtorch as the Java wrapper.

**Comment by fzwqq** [comment]
> Make sure you're using the same version of libtorch as the Java wrapper.
---
Thanks for replying.
I try to compile with javac and java command. 
Specifically,  the version of JDK and Libtorch are 1.8 and 1.5(stable Pre-cxx11 ABI) separately.
The dependence packages that I download are "pytorch_java_only-1.4.0.1.jar", "fbjni-java-only-0.0.3.jar" and "nativeloader-0.8.2.jar". 
---
More details are shown below.
*  libtorch 
![image](https://user-images.githubusercontent.com/12872935/80571062-38724c00-89fc-11ea-9325-a2324a3abf45.png)
* jdk & LIBRARY_PATH
![image](https://user-images.githubusercontent.com/12872935/80571345-c2bab000-89fc-11ea-81e9-c57de7b1a189.png)
* the dependence package I download
![image](https://user-images.githubusercontent.com/12872935/80571582-247b1a00-89fd-11ea-99bc-93da91e21a07.png)
---
1. Then, when I follow the tutorial step by step, it actually works.
![image](https://user-images.githubusercontent.com/12872935/80571690-568c7c00-89fd-11ea-88ff-c8398a63f82a.png)
2. However, when I use the command line, it output like this.
![image](https://user-images.githubusercontent.com/12872935/80571993-d286c400-89fd-11ea-8b31-04776613dfb6.png)
---
I am not sure what the version of the packages is definitely correct. 
Thanks again.

**Comment by dreiss** [comment]
Try running `./gradlew --info run`.  It will show you the exact command that it is running.

**Comment by fzwqq** [comment]
> Try running `./gradlew --info run`. It will show you the exact command that it is running.

---
Thanks for the help. 
After trying running ./gradlew --info run, I think I found the problem. Specifically, it is the version of pytorch-java-only. The detail is shown below. 
![image](https://user-images.githubusercontent.com/12872935/80684838-93707580-8ac6-11ea-8b43-5ec83c97ac56.png)
However, I am really curious why the Gradle could work. In the tutorial, it indicates that only when using the "NIGHTLY" Libtorch, the code should invoke org.pytorch:pytorch_java_only:1.5.0-SNAPSHOT. 
![image](https://user-images.githubusercontent.com/12872935/80689925-560fe600-8ace-11ea-96b6-a34dd77ae583.png)
But I am pretty sure that my Libtorch is a 1.5 ""stable"" version. So, I have been always used the pytorch-java-only 1.4 instead of 1.5. 
After changing the version of pytorch-java-only from 1.4 to 1.5, java executes normally.
![image](https://user-images.githubusercontent.com/12872935/80690494-29100300-8acf-11ea-8256-d2dba6005e22.png)

---
Or, that's to say, I shouldn't install "stable". By default, it is only supporting "nightly", right?

**Comment by fzwqq** [comment]
Thx. The issue has done.
