### ISSUE TITLE
any instructions on how to use the downloaded libtorch in Maven project?

### ISSUE THREAD

**Issue by xiaonanchong** [pytorch/java-demo#15]
I am not familiar with Maven and I want to get some help on how to use the same libtorch in a Maven project, could anyone give me some hint?

**Comment by dreiss** [comment]
Any Maven tutorial should point you in the right direction.  The dependency you need is `org.pytorch:pytorch_java_only:1.9.0`.  Follow the directions in this demo repo for setting up libtorch.
