### ISSUE TITLE
LIBTORCH_HOME not present in environment

### ISSUE THREAD

**Issue by sami-badawi** [pytorch/java-demo#18]
Trying to run the java-demo.
When running:

```
java-demo $ ./gradlew run

LIBTORCH_HOME not present in environment
```

I used Conda install or pytorch with version 1.6. 

```
conda install pytorch
```

That did not create anything that I could point LIBTORCH_HOME to.

I also tried a 
```
pip3 install torch==1.6.0 torchvision==0.7.0
```

Do you need to install Pytorch from source to get java-demo working?

**Comment by 1789120321** [comment]
First, download Libtorch.zip from the official website.
Second,  run the command : gedit ~/.bashrc and add the command : export LIBTORCH_HOME=/usr/libtorch(the path to ibtorch).
Finally, update environment variables and you can get java-demo working.

**Comment by sami-badawi** [comment]
Thanks 1789120321.

I tried to follow your advice:

```
wget https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.7.1.zip 
unzip ibtorch-macos-1.7.1.zip
export LIBTORCH_HOME="~/code/java/libtorch"
export USE_LIBTORCH_NIGHTLY=1
export JAVA_HOME=$(/usr/libexec/java_home)
./gradlew run
```

It failed with message:

```
> Task :run
Exception in thread "main" java.lang.NoSuchMethodError: Method org.pytorch.NativePeer.initHybrid(Ljava/lang/String;I)Lcom/facebook/jni/HybridData; not found
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
```

------

I also tried this install:
```
brew install libtorch
LIBTORCH_HOME="/usr/local/Cellar/libtorch/1.7.1"
export USE_LIBTORCH_NIGHTLY=1
touch /usr/local/Cellar/libtorch/1.7.1/build-version
./gradlew run
```

It failed with message:
```
> Task :run FAILED
Exception in thread "main" java.lang.UnsatisfiedLinkError: no pytorch_jni in java.library.path: [/usr/local/Cellar/libtorch/1.7.1/lib]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
```

**Comment by sami-badawi** [comment]
Looks like Gradle script is slightly out of date. I made a PR bumping the version of PyTorch to 1.7.1 and adding a more detailed build example to the documentation: https://github.com/pytorch/java-demo/pull/19
