### ISSUE TITLE
no pytorch_jni in java.library.path in linux

### ISSUE THREAD

**Issue by anandvsr** [pytorch/java-demo#21]
I want to run my pytorch model into Java so I converted to torchscript.

I clone this git repo, and tried to run.
but caused with exception.
![image](https://user-images.githubusercontent.com/66105422/111667672-f6800d80-883a-11eb-8649-008251a0d664.png)

while running `gradle run` the exception wan thrown

**Comment by anandvsr** [comment]
@dreiss

**Comment by dreiss** [comment]
Not sure what would cause this.  Please make sure that libpytorch_jni.so is present in that directory.  Under Linux, strace might show you what files the JVM is looking for.
