### ISSUE TITLE
how and where is it better to install the LIBTORCH library localy for the project?

### ISSUE THREAD

**Issue by vit1967** [pytorch/java-demo#3]
how and where is it better to install the LIBTORCH library localy for the project in linux(Ubuntu)?
While make proj Intellij idea write Error: "A problem occurred evaluating root project 'java-demo'. > LIBTORCH_HOME not present in environment."

**Comment by dreiss** [comment]
I personally put it in `$HOME/opt/libtorch`, but it doesn't matter where you install it.

I'm not sure if there's an easy way to configure IntelliJ to pass environment variables to gradle.  Maybe you could export `LIBTORCH_HOME` before launching IntelliJ from the command line?  Or you could edit `build.gradle` to hard-code the libtorch path, or get it from a property file.
