### ISSUE TITLE
Does this binding for java a full version?

### ISSUE THREAD

**Issue by rayfalling** [pytorch/java-demo#4]
Can I train model by using java only? 
Currently my team is using swig to warpper libtorch c++ frontend to java.

**Comment by dreiss** [comment]
No.  The current bindings are for inference only.

**Comment by saudet** [comment]
@rayfalling That's something we can now do with the JavaCPP Presets for PyTorch though:
https://github.com/bytedeco/javacpp-presets/blob/master/pytorch/samples/SimpleMNIST.java
Please refer to https://github.com/pytorch/pytorch/issues/58973 for a discussion about that.
