### ISSUE TITLE
the torch java_only-1.4.0.jar is not compatible with java 7

### ISSUE THREAD

**Issue by ares89** [pytorch/java-demo#7]
the torch java_only-1.4.0.jar is not compatible with java 7,
how to package a jar for java 7?
thank you.

**Comment by dreiss** [comment]
Java 7 reached end-of-life in 2015 and is not supported.  You can try building it yourself, but you will be on your own in terms of support.  In the pytorch repository cd into `android/pytorch_android/host` and run `gradle assemble`.

**Comment by suyashcjoshi** [comment]
It would be helpful to mention the minimum Java version supported in the README doc.

**Comment by ares89** [comment]
not only the pytorch_java_only but also the dependency fbjni were built with java 8 but not use the feature of java 8.
